### ISSUE TITLE
Update0.0.1

### ISSUE THREAD

**Issue by wikicrafter** [bumbeishvili/georgian-tech-communities#14]
Add this screen to the social preview  on settings
![image](https://user-images.githubusercontent.com/22988682/132388624-64458f45-af68-478c-8587-2bc0ded00960.png)

**Comment by bumbeishvili** [comment]
Did not know, thank you

**Comment by levanijintcharadze** [comment]
როგორც ვიცი Github-ი ახალ feature-ზე მუშაობს,
რეპოზიტორიის, PR-ის, კომიტის ან Issue-ს ბმულის გაზირებისას ავტომატურად აგენერირებს მეტა მონაცემებს, მათ შორის Social Preview სურათებს. ჯერ ჯერობით მხოლოდ რამდენიმე რეპოზიტორიაზეა მხარდაჭერილი

შეგიძლიათ Twitter-ზე [**thread**](https://twitter.com/JasonEtco/status/1380194813140725761)-საც გადახედოთ 

![image](https://user-images.githubusercontent.com/10853989/132410463-522ed602-ab3a-4b8e-ac99-70051aa7022e.png)

![image](https://user-images.githubusercontent.com/10853989/132410423-7dec9608-4b92-4546-a11d-1f895e81e515.png)

**Comment by bumbeishvili** [comment]
ეს პრევიუ მეც შევამჩნიე

**Comment by wikicrafter** [comment]
ხო, უბრალოდ ეგ ფუნქცია არ დაგიგენერირებს იმ სურათს რაც გინდა რომ იყოს გაზიარებისას, მაგალითად სოციალურ გვერდებზე.
